### PR TITLE
Add custom fields to body

### PR DESCRIPTION
**Pull request by jeffm2001**
When the body is created automatically from form inputs, this allows custom fields to be included. The form name for custom fields should be "custom[key]" (where key is the name of the field).

### CODE REVIEW

**Comment by j-ro** [comment]
This looks great! I want to get some time to try it out a bit before I merge, but looks really good. Thanks!

**Comment by j-ro** [comment]
Ok, finally had a chance to look this over! Few comments:

1. If there is a custom field is on the page but it is left blank, you get a blank custom fields object on person. This is probably fine for all APIs, but convention on this plugin is not to have the parent object at all (try it without sending an email, say, and see that no email block gets outputted on the JSON).

2. This works great with text inputs, radios, and checkboxes, but not with selects or textareas, so probably want to include those too, though that seems to be true with every type of data here, so you can leave that one for me if you'd like.

3. Want to update the documentation in the gh-pages branch too?

**Comment by jeffm2001** [comment]
Ok, fixed 1 & 2, will create a separate PR for the documentation

**Comment by j-ro** [comment]
Probably doesn't fix 2, right? But 2 doesn't work for anything right now, so I can take that on...

If that's your understanding too, I think this is ready to merge.

**Comment by jeffm2001** [comment]
Yeah, it should work for 2. `$(':input')` finds all types of form fields, and `$.serializeArray()` handles collecting values from selects and textareas.

**Comment by j-ro** [comment]
neato! I'm going to port that to other things. Merged!

**Pull request merged**
